# .github/workflows/update_pluto_playlist.yml

name: Update PlutoTV Playlist

permissions:
  contents: read
  pages: write
  id-token: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlink

      - name: Generate playlist
        run: python plutotv_freaksandgeeks.py

      - name: Prepare Pages directory
        run: |
          mkdir -p public
          mv output/freaks_and_geeks.m3u public/playlist.m3u

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
