# .github/workflows/update_pluto_playlist.yml

name: Update PlutoTV Playlist

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install --upgrade pip

    - name: Generate playlist
      run: python plutotv_freaksandgeeks.py

    - name: Move playlist to root
      run: mv output/freaks_and_geeks.m3u .

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        publish_branch: gh-pages
        keep_files: true
        force_orphan: true
        allow_empty_commit: true
